### ISSUE TITLE
Missing "store" property

### ISSUE THREAD

**Issue by nolanlawson** [tivac/eslint-plugin-svelte#1]
I think [this list](https://github.com/tivac/eslint-plugin-svelte/blob/d179d1a5e1348af9f192ff3b8282498d55cbbc25/rules/property-ordering.js#L36-L50) should contain `"store"` as well?

**Comment by tivac** [comment]
Thanks! I'll take a look in a hour or two and see what else I might've missed. Is there a complete list of those prop names somewhere that you know of?

**Comment by nolanlawson** [comment]
Not that I know of, no…

**Comment by tivac** [comment]
Fixed in `1.1.0`, thanks!
