### ISSUE TITLE
Enforce source order

### ISSUE THREAD

**Issue by ghost** [tivac/eslint-plugin-svelte#2]
If possible I would like a check to ensure your components are in html, javascript, css (or whatever; but not necessarily configurable) order. e.g.

``` html
<main>My component</main>
<script>export default {...}</script>
<style>main {...}</style>
```

**Comment by tivac** [comment]
I like that idea, but it's not going to be possible with ESLint currently as far as I know.

The only way to use eslint with a svelte component is by also using `eslint-plugin-html`, which passes the contents of `<script>` tags to the plugins. The plugins never see the entire contents of the svelte component so it's not possible to write a rule like that.

An HTML linter might be able to do it. I'm not up to date on the current best practices there though.
